spring:
  # Database Configuration - using system PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/budget_tracker
    username: ${USER:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  # Flyway Migration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  # Disable Redis for local testing
  data:
    redis:
      repositories:
        enabled: false
  cache:
    type: simple  # Use simple in-memory cache instead of Redis

  # Disable Kafka for local testing
  kafka:
    enabled: false

# Application Configuration
app:
  jwt:
    secret: local-dev-secret-key-change-this-make-it-very-long-for-production-at-least-256-bits
    expiration: 86400000  # 24 hours
    refresh-expiration: 604800000  # 7 days

  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001
    allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    allowed-headers: "*"
    allow-credentials: true

  # Disable features that require external services
  features:
    bank-integration: false
    ocr-receipts: false
    ml-categorization: false
    kafka-events: false
    redis-cache: false
    s3-storage: false

# Logging
logging:
  level:
    root: INFO
    com.budgettracker: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# Server
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
